import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../core/database/app_database.dart';  // For Patient & Encounter types
//import '../theme/app_theme.dart';

/// Generates a patient-readable visit summary PDF with embedded QR code
/// for seamless import into MyPulse (as per MVP decks: day-one benefit)
Future<void> generatePatientSummary({
  required BuildContext context,
  required WidgetRef ref,
  required Patient patient,
  required Encounter encounter,
  required List<Event> notes,  // Clinical notes (SOAP, etc.)
  String shareUrl = 'https://mypulse.patek.xyz/import?encounter=',  // Placeholder secure link
}) async {
  final pdf = pw.Document();

  // Capture QR code as image
  final qrKey = GlobalKey();
  final qrImage = await _captureQrCode(qrKey, '${shareUrl}${encounter.id}');

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      header: (context) => pw.Container(
        alignment: pw.Alignment.centerLeft,
        child: pw.Text(
          'PulseEdge Visit Summary',
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey900,
          ),
        ),
      ),
      footer: (context) => pw.Container(
        alignment: pw.Alignment.center,
        child: pw.Text(
          'Generated by PulseEdge • Patient-readable only • Page ${context.pageNumber} of ${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
        ),
      ),
      build: (context) => [
        pw.Header(
          level: 0,
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Patient: ${patient.fullName}', style: const pw.TextStyle(fontSize: 18)),
                  pw.Text('Encounter Date: ${encounter.createdAt.toLocal().toString().substring(0, 10)}'),
                  pw.Text('Unit: ${encounter.unitName} • Type: ${encounter.type}'),
                ],
              ),
              if (qrImage != null)
                pw.Image(pw.MemoryImage(qrImage), width: 120, height: 120),
            ],
          ),
        ),
        pw.SizedBox(height: 20),
        pw.Divider(color: PdfColors.grey400),
        pw.SizedBox(height: 20),

        pw.Text(
          'Your Visit Summary',
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.grey800),
        ),
        pw.SizedBox(height: 12),
        pw.Text(
          'This is a simplified, patient-readable summary of your visit. '
          'For full clinical details, consult your doctor. '
          'Scan the QR code to import into MyPulse for your personal health timeline.',
          style: const pw.TextStyle(fontSize: 14),
        ),
        pw.SizedBox(height: 20),

        pw.Text('Clinical Notes', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        if (notes.isEmpty)
          pw.Text('No notes recorded for this visit.')
        else
          ...notes.map((note) => pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(note.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.Text(note.bodyText ?? ''),
                  pw.SizedBox(height: 12),
                ],
              )),

        pw.Spacer(),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey200,
            borderRadius: pw.BorderRadius.circular(12),
          ),
          child: pw.Column(
            children: [
              pw.Text(
                'Import to MyPulse',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                'Scan this QR code with the MyPulse app to securely add this visit to your personal health record.',
                textAlign: pw.TextAlign.center,
              ),
            ],
          ),
        ),
      ],
    ),
  );

  // Share/print the PDF
  await Printing.layoutPdf(
    onLayout: (format) async => pdf.save(),
    name: 'PulseEdge_Summary_${patient.fullName.replaceAll(' ', '_')}_${DateTime.now().toIso8601String().substring(0, 10)}.pdf',
  );
}

/// Helper: Render QR code widget to image bytes
Future<Uint8List?> _captureQrCode(GlobalKey key, String data) async {
  try {
    final boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
    final image = await boundary.toImage(pixelRatio: 3.0);
    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    return byteData?.buffer.asUint8List();
  } catch (e) {
    debugPrint('QR capture error: $e');
    return null;
  }
}

/// QR Code Widget (used internally for capture)
class _QrCodeWidget extends StatelessWidget {
  final String data;

  const _QrCodeWidget({required this.data});

  @override
  Widget build(BuildContext context) {
    return RepaintBoundary(
      child: QrImageView(
        data: data,
        version: QrVersions.auto,
        size: 200,
        backgroundColor: Colors.white,
        foregroundColor: const Color(0xFF755659),  // Your brand primary
        errorCorrectionLevel: QrErrorCorrectLevel.H,
        padding: const EdgeInsets.all(12),
      ),
    );
  }
}